rules:
    twig.disabled_escaper:
        enabled: false
    symfony.app.sensitive_data_found_in_application_configuration:
        enabled: false
global_exclude_dirs:
    - bower_components
    - node_modules
exclude_patterns:
    - phpunit-6.1.phar
