global_exclude_dirs:
    - bower_components
    - node_modules
    - src/AppBundle/DataFixtures
exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - app/config/vendors/fos_elastica.yml
    - web/config.php
    - web/app_*.php
    - phpunit-6.1.phar
