language: php
php:
  - '7.0'
  - '7.1'

install:
  - composer install

before_script:
  - bin/console do:da:cr -e=test > /dev/null
  - bin/console do:sc:cr -e=test > /dev/null

script:
  - vendor/bin/behat
