sudo: required

language: php
php:
  - '7.0'
  - '7.1'

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose start

install:
  - composer install

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - bin/console do:da:cr -e=test
  - bin/console do:sc:cr -e=test

script:
  - vendor/bin/behat