version: "3"

services:
    db:
        image: mysql:5.7
        container_name: symfonytodo_db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            symfony_app:
                aliases:
                    - mysql
    app:
        build: docker/app
        container_name: symfonytodo_app
        ports:
            - "8080:80"
            - "6081:6081"
        depends_on:
            - db
            - elasticsearch
        volumes:
            - app-sync:/code:nocopy
        networks:
            - symfony_app
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        container_name: symfonytodo_elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            symfony_app:
                aliases:
                    - elasticsearch
    redis:
        image: redis:3.0
        container_name: symfonytodo_redis
        networks:
            symfony_app:
                aliases:
                    - redis

volumes:
    esdata:
        driver: local
    app-sync:
      external: true

networks:
    symfony_app:


