<?php

declare(strict_types=1);

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getCountByDays(User $user, int $days)
    {
        return $this->getUsersTaskQuery($user)
            ->andWhere('t.createdAt > :minusDays')
            ->groupBy('date')
            ->orderBy('date')
            ->setParameter('minusDays', (new \DateTime())->modify("- $days days"))
            ->select('date(t.createdAt) as date, COUNT(\'date\') as counter ')
            ->getQuery()->getArrayResult();
    }

    public function getDoneUndoneCount(User $user)
    {
        return $this->getUsersTaskQuery($user)
            ->groupBy('t.done')
            ->select('t.done as done, count(t.done) as counter')
            ->getQuery()->getArrayResult();
    }

    private function getUsersTaskQuery(User $user)
    {
        return $this->createQueryBuilder('t')
            ->innerJoin('t.user', 'u')
            ->where('u.id = :userId')
            ->setParameter('userId', $user->getId());
    }
}
