app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation
api:
    type: rest
    resource: "routing_api.yml"
    prefix: /api
logout:
   path: /logout
homepage:
   path: /
   defaults: { _controller: AppBundle:Web/Task:index }
   methods: GET
