# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        autowire: true
    app.password_encode:
        class: AppBundle\EventListener\PasswordEncodeListener
        autowire: true
        tags:
          - { name: doctrine.event_listener, event: prePersist}
    user_provider:
        class: AppBundle\Security\UserProvider
        autowire: true
    app.form.type.task:
        class: AppBundle\Form\Type\TaskType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.type.task_no_image:
        class: AppBundle\Form\Type\TaskTypeWithoutImage
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
